### ISSUE TITLE
Identifier 'getProjectType' has already been declared

### ISSUE THREAD

**Issue by MrSunshyne** [whoiskatrin/npm-copilot#2]
I tried running this using the instructions in the README but ended up with this error:

```bash
npm i -g npm-copilot

npm-copilot
file:///Users/sun/.nvm/versions/node/v16.19.1/lib/node_modules/npm-copilot/error-listener.js:54
function getProjectType() {
^

SyntaxError: Identifier 'getProjectType' has already been declared
    at ESMLoader.moduleStrategy (node:internal/modules/esm/translators:119:18)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:468:14)
    at async link (node:internal/modules/esm/module_job:67:21)

```

I'm running on macOS Ventura and Node v16.19.1

Happy to provide more info to help debug this.

My goal was to check if this also works with other frameworks like vue/nuxt. They also start with `npm run dev`.
I didn't see any Next.js specific code in the source of this project, but the readme mentions Next.js quite heavily. 
I tested with a fresh NextJS install and a Vue project both gave me the same error mentioned above.

**Comment by radosek** [comment]
Same for me. Next.js project with React.
`Node.js v19.8.1` tested also v16/18

**Comment by whoiskatrin** [comment]
this is fixed now! I messed up a bit with packages
